import dotenv from 'dotenv';
dotenv.config();

import mongoose from 'mongoose';
import Connection from './database/db.js';
import Language from './models/Language.js';
import Translation from './models/Translation.js';

const allTranslations = {
    // English
    en: {
        // Navigation & General
        "Home": "Home",
        "Blogs": "Blogs",
        "Login": "Login",
        "Sign In": "Sign In",
        "Sign Up": "Sign Up",
        "Signup": "Signup",
        "Register": "Register",
        "Dashboard": "Dashboard",
        "About": "About",
        "About Us": "About Us",
        "About Me": "About Me",
        "Contact": "Contact",
        "Contact Us": "Contact Us",
        "Write": "Write",
        "Signed in as": "Signed in as",
        "Logout": "Logout",
        "Payment History": "Payment History",
        "Latest Blogs": "Latest Blogs",
        "Read More": "Read More",
        "All": "All",
        "Welcome to My Blog": "Welcome to My Blog",
        "A place where I share my thoughts and experiences": "A place where I share my thoughts and experiences",
        "Search blogs, topics, authors...": "Search blogs, topics, authors...",
        "No posts found": "No posts found",
        "Try a different search term": "Try a different search term",
        "No published posts in this category yet": "No published posts in this category yet",
        "My Dashboard": "My Dashboard",
        "Manage your blog posts here. Drafts are only visible to you.": "Manage your blog posts here. Drafts are only visible to you.",
        "Create New Blog": "Create New Blog",
        "You haven't written any blogs yet": "You haven't written any blogs yet",
        "Share your ideas with the world today.": "Share your ideas with the world today.",
        "Start Writing": "Start Writing",

        // Admin General & Dashboard
        "Blog Admin Dashboard": "Blog Admin Dashboard",
        "Overview of your blog content, users, categories, and inquiries": "Overview of your blog content, users, categories, and inquiries",
        "Overview of your blog content, users, categories, and inquiries.": "Overview of your blog content, users, categories, and inquiries.",
        "TOTAL BLOG POSTS": "TOTAL BLOG POSTS",
        "CATEGORIES": "CATEGORIES",
        "REGISTERED USERS": "REGISTERED USERS",
        "CONTACT INQUIRIES": "CONTACT INQUIRIES",
        "LOGIN HISTORY": "LOGIN HISTORY",
        "View all Posts": "View all Posts",
        "View Categories": "View Categories",
        "Manage Users": "Manage Users",
        "View Inquiries": "View Inquiries",
        "View Login Logs": "View Login Logs",
        "Clear cache": "Clear cache",
        "Administrator": "Administrator",
        "Admin Menu": "Admin Menu",
        "Profile": "Profile",
        "Messages": "Messages",
        "Settings": "Settings",
        "Winning is a habit": "Winning is a habit",

        // Admin Sidebar & Menus
        "Blog Posts": "Blog Posts",
        "Categories": "Categories",
        "Users": "Users",
        "Website Setup": "Website Setup",
        "Homepage Settings": "Homepage Settings",
        "Header": "Header",
        "Footer": "Footer",
        "Pages": "Pages",
        "Appearance": "Appearance",
        "Setup & Configuration": "Setup & Configuration",
        "Feature Activation": "Feature Activation",
        "Language": "Language",
        "SMTP Setting": "SMTP Setting",
        "Payment Methods": "Payment Methods",
        "Google (reCAPTCHA & Firebase)": "Google (reCAPTCHA & Firebase)",
        "Staff": "Staff",
        "All Staff": "All Staff",
        "Staff Permissions": "Staff Permissions",
        "Contact Enquiries": "Contact Enquiries",
        "User Login History": "User Login History",
        "Activity Logs": "Activity Logs",
        "Category Management": "Category Management",
        "Add Category": "Add Category",
        "Category Name": "Category Name",
        "Edit Category": "Edit Category",
        "Add New Category": "Add New Category",
        "Save Category": "Save Category",
        "User Management": "User Management",
        "Add User": "Add User",
        "Edit User": "Edit User",
        "Post Management": "Post Management",
        "Add Post": "Add Post",

        // File System & Redis Configuration
        "admin.fileSystem": "File System Configuration",
        "File System Configuration": "File System Configuration",
        "Configure storage drivers, cloud S3 credentials, cache/session drivers, and Redis.": "Configure storage drivers, cloud S3 credentials, cache/session drivers, and Redis.",
        "S3 File System Credentials": "S3 File System Credentials",
        "Backblaze File System Credentials": "Backblaze File System Credentials",
        "AWS S3 File System Activation": "AWS S3 File System Activation",
        "Backblaze File System Activation": "Backblaze File System Activation",
        "Local File System Activation": "Local File System Activation",
        "Enable AWS S3 Driver": "Enable AWS S3 Driver",
        "Enable Backblaze Driver": "Enable Backblaze Driver",
        "Enable Local Storage Driver": "Enable Local Storage Driver",
        "Cache & Session Driver": "Cache & Session Driver",
        "CACHE_DRIVER": "CACHE_DRIVER",
        "SESSION_DRIVER": "SESSION_DRIVER",
        "file": "file",
        "redis": "redis",
        "Redis Configuration (If you use redis as any of the drivers)": "Redis Configuration (If you use redis as any of the drivers)",
        "Redis Configuration": "Redis Configuration",
        "REDIS_HOST": "REDIS_HOST",
        "REDIS_PASSWORD": "REDIS_PASSWORD",
        "REDIS_PORT": "REDIS_PORT",
        "AWS_ACCESS_KEY_ID": "AWS_ACCESS_KEY_ID",
        "AWS_SECRET_ACCESS_KEY": "AWS_SECRET_ACCESS_KEY",
        "AWS_DEFAULT_REGION": "AWS_DEFAULT_REGION",
        "AWS_BUCKET": "AWS_BUCKET",
        "AWS_URL": "AWS_URL",
        "BACKBLAZE_ACCESS_KEY_ID": "BACKBLAZE_ACCESS_KEY_ID",
        "BACKBLAZE_SECRET_ACCESS_KEY": "BACKBLAZE_SECRET_ACCESS_KEY",
        "BACKBLAZE_DEFAULT_REGION": "BACKBLAZE_DEFAULT_REGION",
        "BACKBLAZE_BUCKET": "BACKBLAZE_BUCKET",
        "BACKBLAZE_ENDPOINT": "BACKBLAZE_ENDPOINT",
        "BACKBLAZE_URL": "BACKBLAZE_URL",
        "Test Connection": "Test Connection",
        "Test Redis Connection": "Test Redis Connection",
        "Redis connected successfully": "Redis connected successfully",
        "File System activation updated to": "File System activation updated to",
        "saved successfully": "saved successfully",

        // AIZ Uploader & Uploaded Files Management
        "admin.uploadedFiles": "Uploaded Files",
        "Uploaded Files": "Uploaded Files",
        "All uploaded files": "All uploaded files",
        "Upload New File": "Upload New File",
        "Back to uploaded files": "Back to uploaded files",
        "Drag & drop your files": "Drag & drop your files",
        "Select File": "Select File",
        "Upload New": "Upload New",
        "Sort by newest": "Sort by newest",
        "Sort by oldest": "Sort by oldest",
        "Sort by smallest": "Sort by smallest",
        "Sort by largest": "Sort by largest",
        "Selected Only": "Selected Only",
        "Search your files": "Search your files",
        "No files found": "No files found",
        "0 File selected": "0 File selected",
        "File(s) selected": "File(s) selected",
        "Clear": "Clear",
        "Prev": "Prev",
        "Next": "Next",
        "Add Files": "Add Files",
        "Details Info": "Details Info",
        "Download": "Download",
        "Copy Link": "Copy Link",
        "Delete selection": "Delete selection",
        "File Info": "File Info",
        "File Name": "File Name",
        "File Type": "File Type",
        "File Size": "File Size",
        "Uploaded By": "Uploaded By",
        "Uploaded At": "Uploaded At",
        "File URL": "File URL",
        "Link copied to clipboard": "Link copied to clipboard",
        "File deleted successfully": "File deleted successfully",
        "Selected files deleted successfully": "Selected files deleted successfully",
        "Choose Banner": "Choose Banner",
        "Choose Icon": "Choose Icon",
        "Choose File": "Choose File",
        "Min size 200x200": "Min size 200x200",
        "Min size 32x32": "Min size 32x32",
        "Upload Now": "Upload Now",

        // Language Management Page
        "Default Language": "Default Language",
        "Import App Translations": "Import App Translations",
        "Add New Language": "Add New Language",
        "Save": "Save",
        "Import": "Import",
        "English Translation File": "English Translation File",
        "Choose app_en.arb file": "Choose app_en.arb file",
        "Browse": "Browse",
        "Flutter App Lang Code": "Flutter App Lang Code",
        "RTL": "RTL",
        "Status": "Status",
        "Options": "Options",
        "Code": "Code",
        "Direction": "Direction",
        "Actions": "Actions",
        "Name": "Name",
        "LTR": "LTR",
        "Web Translation": "Web Translation",
        "App Translation": "App Translation",
        "Export": "Export",
        "Edit": "Edit",
        "Delete": "Delete",
        "Add Translation": "Add Translation",
        "Translate": "Translate",
        "Key": "Key",
        "Value": "Value",
        "Search key or value...": "Search key or value...",
        "Language Settings": "Language Settings",
        "Set Default": "Set Default",
        "Active": "Active",
        "Inactive": "Inactive",
        "Disabled": "Disabled",
        "Default": "Default",
        "Yes": "Yes",
        "No": "No",
        "Cancel": "Cancel",
        "Update": "Update",
        "Create": "Create",
        "Submit": "Submit",
        "Close": "Close",
        "Confirm": "Confirm",
        "Are you sure?": "Are you sure?",
        "Select": "Select",
        "Success": "Success",
        "Error": "Error",
        "Loading...": "Loading...",

        // Forms & Common
        "Email": "Email",
        "Email Address": "Email Address",
        "Password": "Password",
        "Confirm Password": "Confirm Password",
        "Full Name": "Full Name",
        "User Name": "User Name",
        "Role": "Role",
        "Title": "Title",
        "Category": "Category",
        "Description": "Description",
        "Content": "Content",
        "Subject": "Subject",
        "Message": "Message",
        "Send Message": "Send Message",
        "Leave a Comment": "Leave a Comment",
        "Comments": "Comments",
        "Publish": "Publish",
        "Draft": "Draft",
        "Published": "Published",
        "Date": "Date",
        "Action": "Action",
        "Search": "Search",
        "Filter": "Filter",
        "Reset": "Reset",
        "Back": "Back",
        "Next": "Next",
        "Previous": "Previous",
        "Showing": "Showing",
        "to": "to",
        "of": "of",
        "entries": "entries",
        "No data available": "No data available",
        "Remember me": "Remember me",
        "Forgot password?": "Forgot password?",
        "Don't have an account?": "Don't have an account?",
        "Already have an account?": "Already have an account?",

        // Dotted keys for backwards compatibility
        "navbar.home": "Home",
        "navbar.blogs": "Blogs",
        "navbar.login": "Login",
        "navbar.dashboard": "Dashboard",
        "navbar.about": "About",
        "navbar.contact": "Contact",
        "navbar.write": "Write",
        "navbar.signedInAs": "Signed in as",
        "navbar.logout": "Logout",
        "navbar.signIn": "Sign In",
        "navbar.payments": "Payment History",
        "blog.latest": "Latest Blogs",
        "blog.readMore": "Read More",
        "blog.category": "All",
        "home.welcome": "Welcome to My Blog",
        "home.subtitle": "A place where I share my thoughts and experiences",
        "home.readMore": "Read More",
        "home.search": "Search blogs, topics, authors...",
        "home.noPosts": "No posts found",
        "home.tryDifferentSearch": "Try a different search term",
        "home.noPublishedPosts": "No published posts in this category yet",
        "about.title": "About Me",
        "about.welcome": "Welcome to My Blog",
        "about.subtitle": "A place where I share my thoughts and experiences",
        "dashboard.title": "My Dashboard",
        "dashboard.subtitle": "Manage your blog posts here. Drafts are only visible to you.",
        "dashboard.create": "Create New Blog",
        "dashboard.empty.title": "You haven't written any blogs yet",
        "dashboard.empty.subtitle": "Share your ideas with the world today.",
        "dashboard.empty.btn": "Start Writing",
        "admin.dashboard": "Dashboard",
        "admin.posts": "Blog Posts",
        "admin.categories": "Categories",
        "admin.users": "Users",
        "admin.websiteSetup": "Website Setup",
        "admin.setupConfig": "Setup & Configuration",
        "admin.homepageSettings": "Homepage Settings",
        "admin.header": "Header",
        "admin.footer": "Footer",
        "admin.pages": "Pages",
        "admin.appearance": "Appearance",
        "admin.featureActivation": "Feature Activation",
        "admin.language": "Language",
        "admin.smtpSetting": "SMTP Setting",
        "admin.paymentMethods": "Payment Methods",
        "admin.googleSettings": "Google (reCAPTCHA & Firebase)",
        "admin.staff": "Staff",
        "admin.allStaff": "All Staff",
        "admin.staffPermissions": "Staff Permissions",
        "admin.contacts": "Contact Enquiries",
        "admin.loginHistory": "User Login History",
        "admin.activityLogs": "Activity Logs",
        "admin.clearCache": "Clear cache",
        "admin.tagline": "Winning is a habit",
        "admin.administrator": "Administrator",
        "admin.menu": "Admin Menu",
        "admin.profile": "Profile",
        "admin.messages": "Messages",
        "admin.settings": "Settings",
        "admin.langTitle": "Database Language Management",
        "admin.langSubtitle": "Create, enable, and switch default system languages stored in MongoDB.",
        "admin.createLanguage": "Create Language",
        "admin.dbLanguages": "Database Languages",
        "admin.tableLanguage": "Language",
        "admin.tableCode": "Code",
        "admin.tableDirection": "Direction",
        "admin.tableDefault": "Default",
        "admin.tableStatus": "Status",
        "admin.tableActions": "Actions",
        "admin.activeNow": "Active Now",
        "admin.switchToThis": "Switch To This",
        "admin.makeDefault": "Make Default",
        "admin.selected": "Selected",
        "admin.active": "Active",
        "admin.disabled": "Disabled",
        "admin.yes": "Yes",
        "admin.setDefault": "Set Default",
        "admin.select": "Select"
    },

    // Hindi
    hi: {
        // Navigation & General
        "Home": "होम",
        "Blogs": "ब्लॉग्स",
        "Login": "लॉगिन",
        "Sign In": "साइन इन",
        "Sign Up": "साइन अप",
        "Signup": "साइन अप",
        "Register": "पंजीकरण करें",
        "Dashboard": "डैशबोर्ड",
        "About": "मेरे बारे में",
        "About Us": "हमारे बारे में",
        "About Me": "मेरे बारे में",
        "Contact": "संपर्क करें",
        "Contact Us": "हमसे संपर्क करें",
        "Write": "लिखें",
        "Signed in as": "के रूप में लॉग इन",
        "Logout": "लॉग आउट",
        "Payment History": "भुगतान इतिहास",
        "Latest Blogs": "नवीनतम ब्लॉग्स",
        "Read More": "और पढ़ें",
        "All": "सभी",
        "Welcome to My Blog": "मेरे ब्लॉग में आपका स्वागत है",
        "A place where I share my thoughts and experiences": "एक ऐसी जगह जहाँ मैं अपने विचार और अनुभव साझा करता हूँ",
        "Search blogs, topics, authors...": "ब्लॉग्स, विषयों, लेखकों को खोजें...",
        "No posts found": "कोई पोस्ट नहीं मिली",
        "Try a different search term": "कोई अलग खोज शब्द आज़माएं",
        "No published posts in this category yet": "इस श्रेणी में अभी तक कोई प्रकाशित पोस्ट नहीं है",
        "My Dashboard": "मेरा डैशबोर्ड",
        "Manage your blog posts here. Drafts are only visible to you.": "अपने ब्लॉग पोस्ट यहाँ प्रबंधित करें। ड्राफ्ट केवल आपको दिखते हैं।",
        "Create New Blog": "नई ब्लॉग बनाएं",
        "You haven't written any blogs yet": "आपने अभी तक कोई ब्लॉग नहीं लिखा है",
        "Share your ideas with the world today.": "आज ही दुनिया के साथ अपने विचार साझा करें।",
        "Start Writing": "लिखना शुरू करें",

        // Admin General & Dashboard
        "Blog Admin Dashboard": "ब्लॉग व्यवस्थापक डैशबोर्ड",
        "Overview of your blog content, users, categories, and inquiries": "आपकी ब्लॉग सामग्री, उपयोगकर्ताओं, श्रेणियों और पूछताछ का अवलोकन",
        "Overview of your blog content, users, categories, and inquiries.": "आपकी ब्लॉग सामग्री, उपयोगकर्ताओं, श्रेणियों और पूछताछ का अवलोकन।",
        "TOTAL BLOG POSTS": "कुल ब्लॉग पोस्ट",
        "CATEGORIES": "श्रेणियां",
        "REGISTERED USERS": "पंजीकृत उपयोगकर्ता",
        "CONTACT INQUIRIES": "संपर्क पूछताछ",
        "LOGIN HISTORY": "लॉगिन इतिहास",
        "View all Posts": "सभी पोस्ट देखें",
        "View Categories": "श्रेणियां देखें",
        "Manage Users": "उपयोगकर्ता प्रबंधित करें",
        "View Inquiries": "पूछताछ देखें",
        "View Login Logs": "लॉगिन लॉग देखें",
        "Clear cache": "कैश साफ़ करें",
        "Administrator": "प्रशासक",
        "Admin Menu": "व्यवस्थापक मेनू",
        "Profile": "प्रोफ़ाइल",
        "Messages": "संदेश",
        "Settings": "सेटिंग्स",
        "Winning is a habit": "जीतना एक आदत है",

        // Admin Sidebar & Menus
        "Blog Posts": "ब्लॉग पोस्ट",
        "Categories": "श्रेणियां",
        "Users": "उपयोगकर्ता",
        "Website Setup": "वेबसाइट सेटअप",
        "Homepage Settings": "होमपेज सेटिंग्स",
        "Header": "हेडर",
        "Footer": "फुटर",
        "Pages": "पेज",
        "Appearance": "उपस्थिति",
        "Setup & Configuration": "सेटअप और कॉन्फ़िगरेशन",
        "Feature Activation": "फ़ीचर सक्रियण",
        "Language": "भाषा",
        "SMTP Setting": "SMTP सेटिंग्स",
        "Payment Methods": "भुगतान तरीके",
        "Google (reCAPTCHA & Firebase)": "गूगल (रीकैप्चा और फायरबेस)",
        "Staff": "स्टाफ",
        "All Staff": "सभी स्टाफ",
        "Staff Permissions": "स्टाफ अनुमतियां",
        "Contact Enquiries": "संपर्क पूछताछ",
        "User Login History": "उपयोगकर्ता लॉगिन इतिहास",
        "Activity Logs": "गतिविधि लॉग",
        "Category Management": "श्रेणी प्रबंधन",
        "Add Category": "श्रेणी जोड़ें",
        "Category Name": "श्रेणी का नाम",
        "Edit Category": "श्रेणी संपादित करें",
        "Add New Category": "नई श्रेणी जोड़ें",
        "Save Category": "श्रेणी सहेजें",
        "User Management": "उपयोगकर्ता प्रबंधन",
        "Add User": "उपयोगकर्ता जोड़ें",
        "Edit User": "उपयोगकर्ता संपादित करें",
        "Post Management": "पोस्ट प्रबंधन",
        "Add Post": "पोस्ट जोड़ें",

        // File System & Redis Configuration
        "admin.fileSystem": "फ़ाइल सिस्टम कॉन्फ़िगरेशन",
        "File System Configuration": "फ़ाइल सिस्टम कॉन्फ़िगरेशन",
        "Configure storage drivers, cloud S3 credentials, cache/session drivers, and Redis.": "स्टोरेज ड्राइवर, क्लाउड S3 क्रेडेंशियल, कैश/सत्र ड्राइवर और रेडिस कॉन्फ़िगर करें।",
        "S3 File System Credentials": "S3 फ़ाइल सिस्टम क्रेडेंशियल",
        "Backblaze File System Credentials": "Backblaze फ़ाइल सिस्टम क्रेडेंशियल",
        "AWS S3 File System Activation": "AWS S3 फ़ाइल सिस्टम सक्रियण",
        "Backblaze File System Activation": "Backblaze फ़ाइल सिस्टम सक्रियण",
        "Local File System Activation": "स्थानीय फ़ाइल सिस्टम सक्रियण",
        "Enable AWS S3 Driver": "AWS S3 ड्राइवर सक्षम करें",
        "Enable Backblaze Driver": "Backblaze ड्राइवर सक्षम करें",
        "Enable Local Storage Driver": "स्थानीय स्टोरेज ड्राइवर सक्षम करें",
        "Cache & Session Driver": "कैश और सत्र ड्राइवर",
        "CACHE_DRIVER": "CACHE_DRIVER",
        "SESSION_DRIVER": "SESSION_DRIVER",
        "file": "file",
        "redis": "redis",
        "Redis Configuration (If you use redis as any of the drivers)": "रेडिस कॉन्फ़िगरेशन (यदि आप किसी भी ड्राइवर के रूप में रेडिस का उपयोग करते हैं)",
        "Redis Configuration": "रेडिस कॉन्फ़िगरेशन",
        "REDIS_HOST": "REDIS_HOST",
        "REDIS_PASSWORD": "REDIS_PASSWORD",
        "REDIS_PORT": "REDIS_PORT",
        "AWS_ACCESS_KEY_ID": "AWS_ACCESS_KEY_ID",
        "AWS_SECRET_ACCESS_KEY": "AWS_SECRET_ACCESS_KEY",
        "AWS_DEFAULT_REGION": "AWS_DEFAULT_REGION",
        "AWS_BUCKET": "AWS_BUCKET",
        "AWS_URL": "AWS_URL",
        "BACKBLAZE_ACCESS_KEY_ID": "BACKBLAZE_ACCESS_KEY_ID",
        "BACKBLAZE_SECRET_ACCESS_KEY": "BACKBLAZE_SECRET_ACCESS_KEY",
        "BACKBLAZE_DEFAULT_REGION": "BACKBLAZE_DEFAULT_REGION",
        "BACKBLAZE_BUCKET": "BACKBLAZE_BUCKET",
        "BACKBLAZE_ENDPOINT": "BACKBLAZE_ENDPOINT",
        "BACKBLAZE_URL": "BACKBLAZE_URL",
        "Test Connection": "कनेक्शन का परीक्षण करें",
        "Test Redis Connection": "रेडिस कनेक्शन का परीक्षण करें",
        "Redis connected successfully": "रेडिस सफलतापूर्वक कनेक्ट हो गया",
        "Redis connection failed": "रेडिस कनेक्शन विफल रहा",
        "File System activation updated to": "फ़ाइल सिस्टम सक्रियण अपडेट किया गया:",
        "saved successfully": "सफलतापूर्वक सहेजा गया",

        // AIZ Uploader & Uploaded Files Management
        "admin.uploadedFiles": "अपलोड की गई फ़ाइलें",
        "Uploaded Files": "अपलोड की गई फ़ाइलें",
        "All uploaded files": "सभी अपलोड की गई फ़ाइलें",
        "Upload New File": "नई फ़ाइल अपलोड करें",
        "Back to uploaded files": "अपलोड की गई फ़ाइलों पर वापस जाएं",
        "Drag & drop your files": "अपनी फ़ाइलों को खींचें और छोड़ें",
        "Select File": "फ़ाइल चुनें",
        "Upload New": "नया अपलोड करें",
        "Sort by newest": "नवीनतम के अनुसार क्रमबद्ध करें",
        "Sort by oldest": "सबसे पुराने के अनुसार क्रमबद्ध करें",
        "Sort by smallest": "सबसे छोटे के अनुसार क्रमबद्ध करें",
        "Sort by largest": "सबसे बड़े के अनुसार क्रमबद्ध करें",
        "Selected Only": "केवल चयनित",
        "Search your files": "अपनी फ़ाइलें खोजें",
        "No files found": "कोई फ़ाइल नहीं मिली",
        "0 File selected": "0 फ़ाइल चयनित",
        "File(s) selected": "फ़ाइलें चयनित",
        "Clear": "साफ़ करें",
        "Prev": "पिछला",
        "Next": "अगला",
        "Add Files": "फ़ाइलें जोड़ें",
        "Details Info": "विस्तृत जानकारी",
        "Download": "डाउनलोड करें",
        "Copy Link": "लिंक कॉपी करें",
        "Delete selection": "चयनित हटाएं",
        "File Info": "फ़ाइल जानकारी",
        "File Name": "फ़ाइल का नाम",
        "File Type": "फ़ाइल का प्रकार",
        "File Size": "फ़ाइल का आकार",
        "Uploaded By": "द्वारा अपलोड किया गया",
        "Uploaded At": "पर अपलोड किया गया",
        "File URL": "फ़ाइल URL",
        "Link copied to clipboard": "लिंक क्लिपबोर्ड पर कॉपी किया गया",
        "File deleted successfully": "फ़ाइल सफलतापूर्वक हटा दी गई",
        "Selected files deleted successfully": "चयनित फ़ाइलें सफलतापूर्वक हटा दी गईं",
        "Choose Banner": "बैनर चुनें",
        "Choose Icon": "आइकन चुनें",
        "Choose File": "फ़ाइल चुनें",
        "Min size 200x200": "न्यूनतम आकार 200x200",
        "Min size 32x32": "न्यूनतम आकार 32x32",
        "Upload Now": "अभी अपलोड करें",

        // Language Management Page
        "Default Language": "डिफ़ॉल्ट भाषा",
        "Import App Translations": "ऐप अनुवाद आयात करें",
        "Add New Language": "नई भाषा जोड़ें",
        "Save": "सहेजें",
        "Import": "आयात करें",
        "English Translation File": "अंग्रेजी अनुवाद फ़ाइल",
        "Choose app_en.arb file": "app_en.arb फ़ाइल चुनें",
        "Browse": "ब्राउज़ करें",
        "Flutter App Lang Code": "फ्लटर ऐप भाषा कोड",
        "RTL": "RTL",
        "Status": "स्थिति",
        "Options": "विकल्प",
        "Code": "कोड",
        "Direction": "दिशा",
        "Actions": "कार्रवाई",
        "Name": "नाम",
        "LTR": "LTR",
        "Web Translation": "वेब अनुवाद",
        "App Translation": "ऐप अनुवाद",
        "Export": "निर्यात करें",
        "Edit": "संपादित करें",
        "Delete": "हटाएं",
        "Add Translation": "अनुवाद जोड़ें",
        "Translate": "अनुवाद करें",
        "Key": "कुंजी",
        "Value": "मान",
        "Search key or value...": "कुंजी या मान खोजें...",
        "Language Settings": "भाषा सेटिंग्स",
        "Set Default": "डिफ़ॉल्ट सेट करें",
        "Active": "सक्रिय",
        "Inactive": "निष्क्रिय",
        "Disabled": "अक्षम",
        "Default": "डिफ़ॉल्ट",
        "Yes": "हाँ",
        "No": "नहीं",
        "Cancel": "रद्द करें",
        "Update": "अपडेट करें",
        "Create": "बनाएं",
        "Submit": "जमा करें",
        "Close": "बंद करें",
        "Confirm": "पुष्टि करें",
        "Are you sure?": "क्या आप सुनिश्चित हैं?",
        "Select": "चुनें",
        "Success": "सफलता",
        "Error": "त्रुटि",
        "Loading...": "लोड हो रहा है...",

        // Forms & Common
        "Email": "ईमेल",
        "Email Address": "ईमेल पता",
        "Password": "पासवर्ड",
        "Confirm Password": "पासवर्ड की पुष्टि करें",
        "Full Name": "पूरा नाम",
        "User Name": "उपयोगकर्ता नाम",
        "Role": "भूमिका",
        "Title": "शीर्षक",
        "Category": "श्रेणी",
        "Description": "विवरण",
        "Content": "सामग्री",
        "Subject": "विषय",
        "Message": "संदेश",
        "Send Message": "संदेश भेजें",
        "Leave a Comment": "टिप्पणी छोड़ें",
        "Comments": "टिप्पणियाँ",
        "Publish": "प्रकाशित करें",
        "Draft": "ड्राफ्ट",
        "Published": "प्रकाशित",
        "Date": "दिनांक",
        "Action": "कार्रवाई",
        "Search": "खोजें",
        "Filter": "फ़िल्टर",
        "Reset": "रीसेट करें",
        "Back": "वापस जाएं",
        "Next": "अगला",
        "Previous": "पिछला",
        "Showing": "दिखा रहा है",
        "to": "से",
        "of": "का",
        "entries": "प्रविष्टियां",
        "No data available": "कोई डेटा उपलब्ध नहीं है",
        "Remember me": "मुझे याद रखें",
        "Forgot password?": "पासवर्ड भूल गए?",
        "Don't have an account?": "खाता नहीं है?",
        "Already have an account?": "पहले से खाता है?",

        // Dotted keys for backwards compatibility
        "navbar.home": "होम",
        "navbar.blogs": "ब्लॉग्स",
        "navbar.login": "लॉगिन",
        "navbar.dashboard": "डैशबोर्ड",
        "navbar.about": "मेरे बारे में",
        "navbar.contact": "संपर्क करें",
        "navbar.write": "लिखें",
        "navbar.signedInAs": "के रूप में लॉग इन",
        "navbar.logout": "लॉग आउट",
        "navbar.signIn": "साइन इन",
        "navbar.payments": "भुगतान इतिहास",
        "blog.latest": "नवीनतम ब्लॉग्स",
        "blog.readMore": "और पढ़ें",
        "blog.category": "सभी",
        "home.welcome": "मेरे ब्लॉग में आपका स्वागत है",
        "home.subtitle": "एक ऐसी जगह जहाँ मैं अपने विचार और अनुभव साझा करता हूँ",
        "home.readMore": "और पढ़ें",
        "home.search": "ब्लॉग्स, विषयों, लेखकों को खोजें...",
        "home.noPosts": "कोई पोस्ट नहीं मिली",
        "home.tryDifferentSearch": "कोई अलग खोज शब्द आज़माएं",
        "home.noPublishedPosts": "इस श्रेणी में अभी तक कोई प्रकाशित पोस्ट नहीं है",
        "about.title": "मेरे बारे में",
        "about.welcome": "मेरे ब्लॉग में आपका स्वागत है",
        "about.subtitle": "एक ऐसी जगह जहाँ मैं अपने विचार और अनुभव साझा करता हूँ",
        "dashboard.title": "मेरा डैशबोर्ड",
        "dashboard.subtitle": "अपने ब्लॉग पोस्ट यहाँ प्रबंधित करें। ड्राफ्ट केवल आपको दिखते हैं।",
        "dashboard.create": "नई ब्लॉग बनाएं",
        "dashboard.empty.title": "आपने अभी तक कोई ब्लॉग नहीं लिखा है",
        "dashboard.empty.subtitle": "आज ही दुनिया के साथ अपने विचार साझा करें।",
        "dashboard.empty.btn": "लिखना शुरू करें",
        "admin.dashboard": "डैशबोर्ड",
        "admin.posts": "ब्लॉग पोस्ट",
        "admin.categories": "श्रेणियां",
        "admin.users": "उपयोगकर्ता",
        "admin.websiteSetup": "वेबसाइट सेटअप",
        "admin.setupConfig": "सेटअप और कॉन्फ़िगरेशन",
        "admin.homepageSettings": "होमपेज सेटिंग्स",
        "admin.header": "हेडर",
        "admin.footer": "फुटर",
        "admin.pages": "पेज",
        "admin.appearance": "उपस्थिति",
        "admin.featureActivation": "फ़ीचर सक्रियण",
        "admin.language": "भाषा",
        "admin.smtpSetting": "SMTP सेटिंग्स",
        "admin.paymentMethods": "भुगतान तरीके",
        "admin.googleSettings": "गूगल (रीकैप्चा और फायरबेस)",
        "admin.staff": "स्टाफ",
        "admin.allStaff": "सभी स्टाफ",
        "admin.staffPermissions": "स्टाफ अनुमतियां",
        "admin.contacts": "संपर्क पूछताछ",
        "admin.loginHistory": "लॉगिन इतिहास",
        "admin.activityLogs": "गतिविधि लॉग",
        "admin.clearCache": "कैश साफ़ करें",
        "admin.tagline": "जीतना एक आदत है",
        "admin.administrator": "प्रशासक",
        "admin.menu": "व्यवस्थापक मेनू",
        "admin.profile": "प्रोफ़ाइल",
        "admin.messages": "संदेश",
        "admin.settings": "सेटिंग्स",
        "admin.langTitle": "डेटाबेस भाषा प्रबंधन",
        "admin.langSubtitle": "MongoDB में संग्रहीत डिफ़ॉल्ट सिस्टम भाषाओं को बनाएं, सक्षम करें और बदलें।",
        "admin.createLanguage": "भाषा बनाएं",
        "admin.dbLanguages": "डेटाबेस भाषाएं",
        "admin.tableLanguage": "भाषा",
        "admin.tableCode": "कोड",
        "admin.tableDirection": "दिशा",
        "admin.tableDefault": "डिफ़ॉल्ट",
        "admin.tableStatus": "स्थिति",
        "admin.tableActions": "कार्रवाई",
        "admin.activeNow": "अभी सक्रिय",
        "admin.switchToThis": "इसे चुनें",
        "admin.makeDefault": "डिफ़ॉल्ट बनाएं",
        "admin.selected": "चयनित",
        "admin.active": "सक्रिय",
        "admin.disabled": "अक्षम",
        "admin.yes": "हाँ",
        "admin.setDefault": "डिफ़ॉल्ट सेट करें",
        "admin.select": "चुनें"
    },

    // Arabic
    ar: {
        // Navigation & General
        "Home": "الرئيسية",
        "Blogs": "المدونات",
        "Login": "تسجيل الدخول",
        "Sign In": "تسجيل الدخول",
        "Sign Up": "إنشاء حساب",
        "Signup": "إنشاء حساب",
        "Register": "تسجيل",
        "Dashboard": "لوحة التحكم",
        "About": "من أنا",
        "About Us": "معلومات عنا",
        "About Me": "من أنا",
        "Contact": "اتصل بي",
        "Contact Us": "اتصل بنا",
        "Write": "اكتب",
        "Signed in as": "مسجل كـ",
        "Logout": "تسجيل الخروج",
        "Payment History": "سجل المدفوعات",
        "Latest Blogs": "أحدث المدونات",
        "Read More": "اقرأ المزيد",
        "All": "الكل",
        "Welcome to My Blog": "مرحبًا بكم في مدونتي",
        "A place where I share my thoughts and experiences": "مكان أشارك فيه أفكاري وتجربتي",
        "Search blogs, topics, authors...": "ابحث في المدونات والمواضيع والمؤلفين...",
        "No posts found": "لا توجد منشورات",
        "Try a different search term": "جرب كلمة بحث مختلفة",
        "No published posts in this category yet": "لا توجد منشورات في هذه الفئة بعد",
        "My Dashboard": "لوحة التحكم الخاصة بي",
        "Manage your blog posts here. Drafts are only visible to you.": "إدارة منشوراتك هنا. المسودات مرئية لك فقط.",
        "Create New Blog": "إنشاء مدونة جديدة",
        "You haven't written any blogs yet": "لم تكتب أي مدونة بعد",
        "Share your ideas with the world today.": "شارك أفكارك مع العالم اليوم.",
        "Start Writing": "ابدأ الكتابة",

        // Admin General & Dashboard
        "Blog Admin Dashboard": "لوحة تحكم إدارة المدونة",
        "Overview of your blog content, users, categories, and inquiries": "نظرة عامة على محتوى المدونة والمستخدمين والفئات والاستفسارات",
        "Overview of your blog content, users, categories, and inquiries.": "نظرة عامة على محتوى المدونة والمستخدمين والفئات والاستفسارات.",
        "TOTAL BLOG POSTS": "إجمالي منشورات المدونة",
        "CATEGORIES": "الفئات",
        "REGISTERED USERS": "المستخدمون المسجلون",
        "CONTACT INQUIRIES": "استفسارات الاتصال",
        "LOGIN HISTORY": "سجل الدخول",
        "View all Posts": "عرض جميع المنشورات",
        "View Categories": "عرض الفئات",
        "Manage Users": "إدارة المستخدمين",
        "View Inquiries": "عرض الاستفسارات",
        "View Login Logs": "عرض سجلات الدخول",
        "Clear cache": "مسح ذاكرة التخزين المؤقت",
        "Administrator": "مدير النظام",
        "Admin Menu": "قائمة الإدارة",
        "Profile": "الملف الشخصي",
        "Messages": "الرسائل",
        "Settings": "الإعدادات",
        "Winning is a habit": "الفوز عادة",

        // Admin Sidebar & Menus
        "Blog Posts": "منشورات المدونة",
        "Categories": "الفئات",
        "Users": "المستخدمون",
        "Website Setup": "إعداد الموقع",
        "Homepage Settings": "إعدادات الصفحة الرئيسية",
        "Header": "الترويسة",
        "Footer": "تذييل الصفحة",
        "Pages": "الصفحات",
        "Appearance": "المظهر",
        "Setup & Configuration": "الإعداد والتكوين",
        "Feature Activation": "تنشيط الميزات",
        "Language": "اللغة",
        "SMTP Setting": "إعدادات SMTP",
        "Payment Methods": "طرق الدفع",
        "Google (reCAPTCHA & Firebase)": "جوجل (reCAPTCHA & Firebase)",
        "Staff": "الموظفون",
        "All Staff": "جميع الموظفين",
        "Staff Permissions": "صلاحيات الموظفين",
        "Contact Enquiries": "استفسارات الاتصال",
        "User Login History": "سجل دخول المستخدمين",
        "Activity Logs": "سجلات النشاط",
        "Category Management": "إدارة الفئات",
        "Add Category": "إضافة فئة",
        "Category Name": "اسم الفئة",
        "Edit Category": "تعديل الفئة",
        "Add New Category": "إضافة فئة جديدة",
        "Save Category": "حفظ الفئة",
        "User Management": "إدارة المستخدمين",
        "Add User": "إضافة مستخدم",
        "Edit User": "تعديل المستخدم",
        "Post Management": "إدارة المنشورات",
        "Add Post": "إضافة منشور",

        // File System & Redis Configuration
        "admin.fileSystem": "إعدادات نظام الملفات",
        "File System Configuration": "إعدادات نظام الملفات",
        "Configure storage drivers, cloud S3 credentials, cache/session drivers, and Redis.": "تكوين برامج تشغيل التخزين، وبيانات اعتماد S3 السحابية، وبرامج تشغيل ذاكرة التخزين المؤقت/الجلسة، وRedis.",
        "S3 File System Credentials": "بيانات اعتماد نظام ملفات S3",
        "Backblaze File System Credentials": "بيانات اعتماد نظام ملفات Backblaze",
        "AWS S3 File System Activation": "تنشيط نظام ملفات AWS S3",
        "Backblaze File System Activation": "تنشيط نظام ملفات Backblaze",
        "Local File System Activation": "تنشيط نظام الملفات المحلي",
        "Enable AWS S3 Driver": "تمكين برنامج تشغيل AWS S3",
        "Enable Backblaze Driver": "تمكين برنامج تشغيل Backblaze",
        "Enable Local Storage Driver": "تمكين برنامج تشغيل التخزين المحلي",
        "Cache & Session Driver": "برنامج تشغيل ذاكرة التخزين المؤقت والجلسة",
        "CACHE_DRIVER": "CACHE_DRIVER",
        "SESSION_DRIVER": "SESSION_DRIVER",
        "file": "file",
        "redis": "redis",
        "Redis Configuration (If you use redis as any of the drivers)": "تكوين Redis (إذا كنت تستخدم redis كأحد برامج التشغيل)",
        "Redis Configuration": "تكوين Redis",
        "REDIS_HOST": "REDIS_HOST",
        "REDIS_PASSWORD": "REDIS_PASSWORD",
        "REDIS_PORT": "REDIS_PORT",
        "AWS_ACCESS_KEY_ID": "AWS_ACCESS_KEY_ID",
        "AWS_SECRET_ACCESS_KEY": "AWS_SECRET_ACCESS_KEY",
        "AWS_DEFAULT_REGION": "AWS_DEFAULT_REGION",
        "AWS_BUCKET": "AWS_BUCKET",
        "AWS_URL": "AWS_URL",
        "BACKBLAZE_ACCESS_KEY_ID": "BACKBLAZE_ACCESS_KEY_ID",
        "BACKBLAZE_SECRET_ACCESS_KEY": "BACKBLAZE_SECRET_ACCESS_KEY",
        "BACKBLAZE_DEFAULT_REGION": "BACKBLAZE_DEFAULT_REGION",
        "BACKBLAZE_BUCKET": "BACKBLAZE_BUCKET",
        "BACKBLAZE_ENDPOINT": "BACKBLAZE_ENDPOINT",
        "BACKBLAZE_URL": "BACKBLAZE_URL",
        "Test Connection": "اختبار الاتصال",
        "Test Redis Connection": "اختبار اتصال Redis",
        "Redis connected successfully": "تم الاتصال بـ Redis بنجاح",
        "Redis connection failed": "فشل الاتصال بـ Redis",
        "File System activation updated to": "تم تحديث تنشيط نظام الملفات إلى:",
        "saved successfully": "تم الحفظ بنجاح",

        // AIZ Uploader & Uploaded Files Management
        "admin.uploadedFiles": "الملفات المرفوعة",
        "Uploaded Files": "الملفات المرفوعة",
        "All uploaded files": "جميع الملفات المرفوعة",
        "Upload New File": "رفع ملف جديد",
        "Back to uploaded files": "العودة إلى الملفات المرفوعة",
        "Drag & drop your files": "اسحب الملفات وأفلتها هنا",
        "Select File": "اختر ملفاً",
        "Upload New": "رفع جديد",
        "Sort by newest": "الترتيب حسب الأحدث",
        "Sort by oldest": "الترتيب حسب الأقدم",
        "Sort by smallest": "الترتيب حسب الأصغر",
        "Sort by largest": "الترتيب حسب الأكبر",
        "Selected Only": "المحدد فقط",
        "Search your files": "ابحث في ملفاتك",
        "No files found": "لم يتم العثور على ملفات",
        "0 File selected": "0 ملف محدد",
        "File(s) selected": "ملفات محددة",
        "Clear": "مسح",
        "Prev": "السابق",
        "Next": "التالي",
        "Add Files": "إضافة الملفات",
        "Details Info": "تفاصيل الملف",
        "Download": "تنزيل",
        "Copy Link": "نسخ الرابط",
        "Delete selection": "حذف المحدد",
        "File Info": "معلومات الملف",
        "File Name": "اسم الملف",
        "File Type": "نوع الملف",
        "File Size": "حجم الملف",
        "Uploaded By": "تم الرفع بواسطة",
        "Uploaded At": "تاريخ الرفع",
        "File URL": "رابط الملف",
        "Link copied to clipboard": "تم نسخ الرابط إلى الحافظة",
        "File deleted successfully": "تم حذف الملف بنجاح",
        "Selected files deleted successfully": "تم حذف الملفات المحددة بنجاح",
        "Choose Banner": "اختر الشعار",
        "Choose Icon": "اختر الأيقونة",
        "Choose File": "اختر ملفاً",
        "Min size 200x200": "الحد الأدنى 200x200",
        "Min size 32x32": "الحد الأدنى 32x32",
        "Upload Now": "ارفع الآن",

        // Language Management Page
        "Default Language": "اللغة الافتراضية",
        "Import App Translations": "استيراد ترجمات التطبيق",
        "Add New Language": "إضافة لغة جديدة",
        "Save": "حفظ",
        "Import": "استيراد",
        "English Translation File": "ملف الترجمة الإنجليزية",
        "Choose app_en.arb file": "اختر ملف app_en.arb",
        "Browse": "استعراض",
        "Flutter App Lang Code": "رمز لغة تطبيق فلاتر",
        "RTL": "RTL",
        "Status": "الحالة",
        "Options": "الخيارات",
        "Code": "الرمز",
        "Direction": "الاتجاه",
        "Actions": "الإجراءات",
        "Name": "الاسم",
        "LTR": "LTR",
        "Web Translation": "ترجمة الويب",
        "App Translation": "ترجمة التطبيق",
        "Export": "تصدير",
        "Edit": "تعديل",
        "Delete": "حذف",
        "Add Translation": "إضافة ترجمة",
        "Translate": "ترجمة",
        "Key": "المفتاح",
        "Value": "القيمة",
        "Search key or value...": "البحث عن مفتاح أو قيمة...",
        "Language Settings": "إعدادات اللغة",
        "Set Default": "تعيين كافتراضي",
        "Active": "نشط",
        "Inactive": "غير نشط",
        "Disabled": "معطل",
        "Default": "افتراضي",
        "Yes": "نعم",
        "No": "لا",
        "Cancel": "إلغاء",
        "Update": "تحديث",
        "Create": "إنشاء",
        "Submit": "إرسال",
        "Close": "إغلاق",
        "Confirm": "تأكيد",
        "Are you sure?": "هل أنت متأكد؟",
        "Select": "تحديد",
        "Success": "نجاح",
        "Error": "خطأ",
        "Loading...": "جارٍ التحميل...",

        // Forms & Common
        "Email": "البريد الإلكتروني",
        "Email Address": "عنوان البريد الإلكتروني",
        "Password": "كلمة المرور",
        "Confirm Password": "تأكيد كلمة المرور",
        "Full Name": "الاسم الكامل",
        "User Name": "اسم المستخدم",
        "Role": "الدور",
        "Title": "العنوان",
        "Category": "الفئة",
        "Description": "الوصف",
        "Content": "المحتوى",
        "Subject": "الموضوع",
        "Message": "الرسالة",
        "Send Message": "إرسال الرسالة",
        "Leave a Comment": "اترك تعليقًا",
        "Comments": "التعليقات",
        "Publish": "نشر",
        "Draft": "مسودة",
        "Published": "تم النشر",
        "Date": "التاريخ",
        "Action": "إجراء",
        "Search": "بحث",
        "Filter": "تصفية",
        "Reset": "إعادة تعيين",
        "Back": "رجوع",
        "Next": "التالي",
        "Previous": "السابق",
        "Showing": "عرض",
        "to": "إلى",
        "of": "من",
        "entries": "مدخلات",
        "No data available": "لا توجد بيانات متاحة",
        "Remember me": "تذكرني",
        "Forgot password?": "نسيت كلمة المرور؟",
        "Don't have an account?": "ليس لديك حساب؟",
        "Already have an account?": "هل لديك حساب بالفعل؟",

        // Dotted keys for backwards compatibility
        "navbar.home": "الرئيسية",
        "navbar.blogs": "المدونات",
        "navbar.login": "تسجيل الدخول",
        "navbar.dashboard": "لوحة التحكم",
        "navbar.about": "من أنا",
        "navbar.contact": "اتصل بي",
        "navbar.write": "اكتب",
        "navbar.signedInAs": "مسجل كـ",
        "navbar.logout": "تسجيل الخروج",
        "navbar.signIn": "تسجيل الدخول",
        "navbar.payments": "سجل المدفوعات",
        "blog.latest": "أحدث المدونات",
        "blog.readMore": "اقرأ المزيد",
        "blog.category": "الكل",
        "home.welcome": "مرحبًا بكم في مدونتي",
        "home.subtitle": "مكان أشارك فيه أفكاري وتجربتي",
        "home.readMore": "اقرأ المزيد",
        "home.search": "ابحث في المدونات والمواضيع والمؤلفين...",
        "home.noPosts": "لا توجد منشورات",
        "home.tryDifferentSearch": "جرب كلمة بحث مختلفة",
        "home.noPublishedPosts": "لا توجد منشورات في هذه الفئة بعد",
        "about.title": "من أنا",
        "about.welcome": "مرحبًا بكم في مدونتي",
        "about.subtitle": "مكان أشارك فيه أفكاري وتجربتي",
        "dashboard.title": "لوحة التحكم",
        "dashboard.subtitle": "إدارة منشوراتك هنا. المسودات مرئية لك فقط.",
        "dashboard.create": "إنشاء مدونة جديدة",
        "dashboard.empty.title": "لم تكتب أي مدونة بعد",
        "dashboard.empty.subtitle": "شارك أفكارك مع العالم اليوم.",
        "dashboard.empty.btn": "ابدأ الكتابة",
        "admin.dashboard": "لوحة التحكم",
        "admin.posts": "منشورات المدونة",
        "admin.categories": "الفئات",
        "admin.users": "المستخدمون",
        "admin.websiteSetup": "إعداد الموقع",
        "admin.setupConfig": "الإعداد والتكوين",
        "admin.homepageSettings": "إعدادات الصفحة الرئيسية",
        "admin.header": "الترويسة",
        "admin.footer": "تذييل الصفحة",
        "admin.pages": "الصفحات",
        "admin.appearance": "المظهر",
        "admin.featureActivation": "تنشيط الميزات",
        "admin.language": "اللغة",
        "admin.smtpSetting": "إعدادات SMTP",
        "admin.paymentMethods": "طرق الدفع",
        "admin.googleSettings": "جوجل (reCAPTCHA & Firebase)",
        "admin.staff": "الموظفون",
        "admin.allStaff": "جميع الموظفين",
        "admin.staffPermissions": "صلاحيات الموظفين",
        "admin.contacts": "استفسارات الاتصال",
        "admin.loginHistory": "سجل دخول المستخدمين",
        "admin.activityLogs": "سجلات النشاط",
        "admin.clearCache": "مسح ذاكرة التخزين المؤقت",
        "admin.tagline": "الفوز عادة",
        "admin.administrator": "مدير النظام",
        "admin.menu": "قائمة الإدارة",
        "admin.profile": "الملف الشخصي",
        "admin.messages": "الرسائل",
        "admin.settings": "الإعدادات",
        "admin.langTitle": "إدارة لغات قاعدة البيانات",
        "admin.langSubtitle": "إنشاء وتفعيل وتبديل لغات النظام الافتراضية المخزنة في MongoDB.",
        "admin.createLanguage": "إنشاء لغة",
        "admin.dbLanguages": "لغات قاعدة البيانات",
        "admin.tableLanguage": "اللغة",
        "admin.tableCode": "الرمز",
        "admin.tableDirection": "الاتجاه",
        "admin.tableDefault": "افتراضي",
        "admin.tableStatus": "الحالة",
        "admin.tableActions": "الإجراءات",
        "admin.activeNow": "نشط الآن",
        "admin.switchToThis": "التبديل إلى هذا",
        "admin.makeDefault": "تعيين كافتراضي",
        "admin.selected": "محدد",
        "admin.active": "نشط",
        "admin.disabled": "معطل",
        "admin.yes": "نعم",
        "admin.setDefault": "تعيين كافتراضي",
        "admin.select": "تحديد"
    }
};

const run = async () => {
    try {
        const username = process.env.DB_USERNAME;
        const password = process.env.DB_PASSWORD;
        await Connection(username, password);
        console.log('Connected to MongoDB.');

        // Ensure languages exist with correct rtl values
        const defaultLangs = [
            { name: "English", code: "en", app_code: "en", flag: "us", dir: "ltr", rtl: 0, isRtl: false, isDefault: true, isActive: true },
            { name: "Hindi", code: "hi", app_code: "in", flag: "in", dir: "ltr", rtl: 0, isRtl: false, isDefault: false, isActive: true },
            { name: "Arabic", code: "ar", app_code: "sa", flag: "sa", dir: "rtl", rtl: 1, isRtl: true, isDefault: false, isActive: true }
        ];

        for (const lang of defaultLangs) {
            await Language.findOneAndUpdate(
                { code: lang.code },
                { $set: lang },
                { upsert: true, new: true }
            );
        }
        console.log('Verified default languages (English, Hindi, Arabic).');

        const ops = [];

        // English (en)
        for (const [key, val] of Object.entries(allTranslations.en)) {
            ops.push({
                updateOne: {
                    filter: { lang: 'en', lang_key: key },
                    update: { $set: { lang: 'en', lang_key: key, lang_value: val } },
                    upsert: true
                }
            });
        }

        // Hindi (hi and in)
        for (const [key, val] of Object.entries(allTranslations.hi)) {
            ops.push({
                updateOne: {
                    filter: { lang: 'hi', lang_key: key },
                    update: { $set: { lang: 'hi', lang_key: key, lang_value: val } },
                    upsert: true
                }
            });
            ops.push({
                updateOne: {
                    filter: { lang: 'in', lang_key: key },
                    update: { $set: { lang: 'in', lang_key: key, lang_value: val } },
                    upsert: true
                }
            });
        }

        // Arabic (ar and sa)
        for (const [key, val] of Object.entries(allTranslations.ar)) {
            ops.push({
                updateOne: {
                    filter: { lang: 'ar', lang_key: key },
                    update: { $set: { lang: 'ar', lang_key: key, lang_value: val } },
                    upsert: true
                }
            });
            ops.push({
                updateOne: {
                    filter: { lang: 'sa', lang_key: key },
                    update: { $set: { lang: 'sa', lang_key: key, lang_value: val } },
                    upsert: true
                }
            });
        }

        console.log(`Executing ${ops.length} bulk translation upserts into MongoDB...`);
        const res = await Translation.bulkWrite(ops);
        console.log('Seeding result:', res.upsertedCount, 'upserted,', res.modifiedCount, 'modified.');

        await mongoose.disconnect();
        console.log('Seeding completed successfully!');
        process.exit(0);
    } catch (err) {
        console.error('Seeding error:', err);
        process.exit(1);
    }
};

run();
